# -*- coding: utf-8 -*-
"""Student Course Feedback.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1idSwQK1OIbIFQ7yQYjuGJ86uE8yTjQjT

# STAT 4910 PROJECT
"""

import pandas as pd

df = pd.read_csv('/content/RateMyProfessor_Sample data.csv')
df.head()

# checking the content of the file

df.columns

df.comments

# getting a feel for what's inside


df['comments'].head(10)
df['comments'].isna().sum()
df['comments'].duplicated().sum()
df['comments'].str.len().describe()

#light cleanup

import re

def clean_text(text):
    if pd.isna(text):
        return ""
    text = text.lower()
    text = re.sub(r'\s+', ' ', text)        # remove extra spaces
    text = re.sub(r'http\S+', '', text)     # remove URLs
    text = re.sub(r'[^a-zA-Z\s]', '', text) # remove weird characters
    return text.strip()

df['clean_text'] = df['comments'].apply(clean_text)
df[['comments', 'clean_text']].head()

"""Now to Auto-Label the sentiment using VADER"""

# installing VADER
!pip install vaderSentiment

from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
analyzer = SentimentIntensityAnalyzer()

# creating labels:

def vader_label(text):
    score = analyzer.polarity_scores(text)['compound']
    if score >= 0.05:
        return 'positive'
    elif score <= -0.05:
        return 'negative'
    else:
        return 'neutral'

df['sentiment'] = df['clean_text'].apply(vader_label)
df[['clean_text', 'sentiment']].head()

#saving this new dataset

df.to_csv('student_feedback_labeled.csv', index=False)


from google.colab import drive
import os
drive.mount('/content/drive')

# Define the directory path
drive_path = '/content/drive/MyDrive/NLP_Project'

# Create the directory if it doesn't exist
if not os.path.exists(drive_path):
    os.makedirs(drive_path)
    print(f"Directory '{drive_path}' created.")

# Then save to your Drive
df.to_csv(os.path.join(drive_path, 'student_feedback_labeled.csv'), index=False)
print(f"File saved to '{os.path.join(drive_path, 'student_feedback_labeled.csv')}'")

from google.colab import drive
drive.mount('/content/drive')

"""# Developing Baseline Models:
The goal here is to build simple machine learning models to classify feedback into *positive*, *neutral*, or *negative*.
These models will act as the benchmark before we move on to transformers.
"""

#Splitting the dataset:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df['clean_text'], df['sentiment'], test_size=0.2, random_state=42)

"""Vectorising the text using `TfidfVectorizer`,




"""

from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(max_features=5000, ngram_range=(1,2))
X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

"""Training baseline models using Logistic regression

"""

from sklearn.linear_model import LogisticRegression
model = LogisticRegression(max_iter=1000)
model.fit(X_train_tfidf, y_train)

"""Evaluating:"""

from sklearn.metrics import classification_report, confusion_matrix
y_pred = model.predict(X_test_tfidf)
print(classification_report(y_test, y_pred))

"""# Step 5: Fine-Tune Transformer Models
 At this point, the objective is to use a more powerful contextual model that understands meaning better than TF-IDF features

Using the Hugging Face Transformers Library:
"""

from transformers import DistilBertTokenizer, DistilBertForSequenceClassification, Trainer, TrainingArguments

"""#"""